module.exports = {
  Avatar: require('./lib/avatar'),
  Box: require('./lib/box'),
  ButtonGroup: require('./lib/button-group'),
  Button: require('./lib/button'),
  Card: require('./lib/card'),
  Checkbox: require('./lib/checkbox'),
  Dialog: require('./lib/dialog'),
  Dropdown: require('./lib/dropdown'),
  FengForm: require('./lib/feng-form'),
  Field: require('./lib/field'),
  Form: require('./lib/form'),
  Gravatar: require('./lib/gravatar'),
  Grid: require('./lib/grid'),
  InputColor: require('./lib/input-color'),
  InputSlider: require('./lib/input-slider'),
  InputSwitch: require('./lib/input-switch'),
  Label: require('./lib/label'),
  Markdown: require('./lib/markdown'),
  Slat: require('./lib/slat'),
  Spinner: require('./lib/spinner'),
  Tabs: require('./lib/tabs'),
  Textarea: require('./lib/textarea')
};
