module.exports = {
  'Avatar': require('./lib/avatar'),
  'ButtonGroup': require('./lib/button-group'),
  'Button': require('./lib/button'),
  'Card': require('./lib/card'),
  'Checkbox': require('./lib/checkbox'),
  'FengForm': require('./lib/feng-form'),
  'Field': require('./lib/field'),
  'Form': require('./lib/form'),
  'Gravatar': require('./lib/gravatar'),
  'Grid': require('./lib/grid'),
  'Label': require('./lib/label'),
  'Spinner': require('./lib/spinner'),
  'Tabs': require('./lib/tabs'),
  'InputColor': require('./lib/input-color'),
  'InputSlider': require('./lib/input-slider'),
  'InputSwitch': require('./lib/input-switch'),
  'Select': require('./lib/select'),
  'Slat': require('./lib/slat')
};
