module.exports = {
  'Link': require('./lib/Link'),
  'button-group': require('./lib/button-group'),
  'button': require('./lib/button'),
  'card': require('./lib/card'),
  'checkbox': require('./lib/checkbox'),
  'feng-form': require('./lib/feng-form'),
  'field': require('./lib/field'),
  'form': require('./lib/form'),
  'gravatar': require('./lib/gravatar'),
  'grid': require('./lib/grid'),
  'label': require('./lib/label'),
  'nav': require('./lib/nav'),
  'spinner': require('./lib/spinner'),
  'tabs': require('./lib/tabs'),
  'InputColor': require('./lib/input-color'),
  'InputSlider': require('./lib/input-slider'),
  'InputSwitch': require('./lib/input-switch'),
  'Select': require('./lib/select')
};
